spring.application.name=mssc-order-service
logging.level.guru=debug
server.port=8081
sfg.brewery.beer-service-host=http://localhost:8080

spring.artemis.user=artemis
spring.artemis.password=artemis

# 1. Disabilita completamente l'esportatore di tracce OpenTelemetry
management.otlp.metrics.export.enabled=false

# 2. Imposta la probabilita' di campionamento a 0 (nessuna traccia viene catturata)
management.tracing.sampling.probability=0.0
