spring.application.name=mssc-order-service
logging.level.guru=debug
server.port=8081
sfg.brewery.beer-service-host=http://localhost:8080

spring.artemis.user=artemis
spring.artemis.password=artemis

# Cattura il 100% dei passaggi (utilizza valori piu' bassi come 0.05 o 0.10 in produzione)
management.tracing.sampling.probability=1.0

# Endpoint del tuo raccoglitore di tracce (es. Jaeger, Tempo, OpenObserve)
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
